name: get-bikereg-latest
run-name: ${{ github.actor }} is updating latest bikereg info
on: [push]
jobs:
  get-bikereg-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install pandas and requests
        run: pip install pandas requests
      - name: update events.json
        run: python app.py
      - name: stage changed files
        run: git add events.json
      - name: commit changes
        run: git commit -m 'sync events.json'
      - name: push changes
        run: git push origin main